baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Fazer as Malas'
primary: true
siteGroup: 1a684aff-7b41-4c95-a7f0-67e30d54a9c3 # Fazer as Malas
sortOrder: 1
