columnSuffix: null
contentColumnType: string
fieldGroup: a790ad74-dcaf-4181-9c9b-618164be689c # Blog Post Fields
handle: postContent
instructions: ''
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
