fieldLayouts:
  0986bd43-3936-406b-aeed-25b6b2d84886:
    tabs:
      -
        elements:
          -
            fieldUid: 63447928-2142-4dfb-8c79-dfa3b2c34376 # Site Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Site Information'
        sortOrder: 1
handle: siteInformation
name: 'Site Information'
sortOrder: 1
