defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  20d47ea2-78fe-4b35-ae01-6068e35ecfc9: # Fazer as Malas
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
